global:
  resolve_timeout: 1m

route:
  # continue: false
  # group_by:
  # - job
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 4h
  receiver: 'default-telegram'
  routes:
  - receiver: 'default-telegram'
    continue: true

receivers:
 
- name: default-telegram
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: #
    chat_id: #
    disable_notifications: false
    http_config:
      follow_redirects: true
    send_resolved: true
    parse_mode: ""
